product_index:
    path:     /
    defaults: { _controller: "MainBundle:Product:index" }
    methods:  GET
product_valable:
    path:     /{id}/valable
    defaults: { _controller: "MainBundle:Product:valable" }
    methods:  GET
product_indexme:
    path:     /myproducts
    defaults: { _controller: "MainBundle:Product:indexme" }
    methods:  GET


product_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "MainBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:      /delete/{id}
    defaults: { _controller: "MainBundle:Product:delete" }


product_change:
    path:     /data
    defaults: { _controller: "MainBundle:Product:projetajax" }
