<?php

namespace MainBundle\Repository;

/**
 * VenteFlashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteFlashRepository extends \Doctrine\ORM\EntityRepository {
  public function active( ){
      $today = new \DateTime('now');

      $qb =$this->createQueryBuilder('v')
          ->andWhere(':today > v.datedebut')
          ->setParameter(':today', $today );

            return $qb->getQuery()->getResult();





    }
    public function attente($user ){

        $today = new \DateTime('now');
        $qb =$this->createQueryBuilder('v')
            ->andWhere(':today < v.datedebut')
            ->andWhere(':user = v.vendeur')





            ->setParameter(':today', $today )
        ->setParameter(':user', $user );

        return $qb->getQuery()->getResult();
    }
}
