<?php

namespace Proxies\__CG__\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \MainBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'libelle', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'marque', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'etat', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'prixProduit', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'flashprice', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'venteflash', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'magasin', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'quantiteStock', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'pourcentagePromotion', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'createdDate', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Duree', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Categorie', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Approuver', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Seller', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'imageFile', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'imageName', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'libelle', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'marque', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'etat', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'prixProduit', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'flashprice', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'venteflash', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'magasin', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'quantiteStock', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'pourcentagePromotion', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'createdDate', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Duree', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Categorie', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Approuver', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'Seller', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'imageFile', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'imageName', '' . "\0" . 'MainBundle\\Entity\\Product' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($Duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$Duree]);

        return parent::setDuree($Duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getApprouver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApprouver', []);

        return parent::getApprouver();
    }

    /**
     * {@inheritDoc}
     */
    public function setApprouver($Approuver)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApprouver', [$Approuver]);

        return parent::setApprouver($Approuver);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$createdDate]);

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque($marque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixProduit', []);

        return parent::getPrixProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixProduit($prixProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixProduit', [$prixProduit]);

        return parent::setPrixProduit($prixProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteStock', []);

        return parent::getQuantiteStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteStock($quantiteStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteStock', [$quantiteStock]);

        return parent::setQuantiteStock($quantiteStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getPourcentagePromotion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPourcentagePromotion', []);

        return parent::getPourcentagePromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPourcentagePromotion($pourcentagePromotion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPourcentagePromotion', [$pourcentagePromotion]);

        return parent::setPourcentagePromotion($pourcentagePromotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($Categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$Categorie]);

        return parent::setCategorie($Categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName($imageName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName', [$imageName]);

        return parent::setImageName($imageName);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName', []);

        return parent::getImageName();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setVenteflash(\MainBundle\Entity\VenteFlash $venteflash = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVenteflash', [$venteflash]);

        return parent::setVenteflash($venteflash);
    }

    /**
     * {@inheritDoc}
     */
    public function getVenteflash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVenteflash', []);

        return parent::getVenteflash();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlashprice($flashprice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlashprice', [$flashprice]);

        return parent::setFlashprice($flashprice);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlashprice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlashprice', []);

        return parent::getFlashprice();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller(\MainBundle\Entity\User $seller = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller', [$seller]);

        return parent::setSeller($seller);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller', []);

        return parent::getSeller();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagasin(\MainBundle\Entity\Magasin $magasin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagasin', [$magasin]);

        return parent::setMagasin($magasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagasin', []);

        return parent::getMagasin();
    }

}
