services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.form.registration:
    class: MainBundle\Form\RegistrationFormType
    tags:
          - { name:form.type,alias: app_user_registration }
  app.form.profile:
    class: MainBundle\Form\ProfileFormType
    tags:
          - { name:form.type,alias: app_user_profile }